version: "3.7"
services:
  db:
    image: postgres
    port:
      - "15432:5432"
    networks:
      - network-backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nest1234
  cache:
    image: redis
    port:
      - "16379:6379"
    networks:
      - network-backend
    volumes:
      - redis_data:/data 

networks:
  network-backend: